### ISSUE TITLE
02-multi_determinant not working

### ISSUE THREAD

**Issue by michaelstreif** [linusjoonho/ipie#152]
When trying to run the example in https://github.com/linusjoonho/ipie/tree/main/examples/02-multi_determinant I get back the following error message: 

> File "/ipie/estimators/local_energy_batch.py", line 101, in local_energy_batch
>     system, hamiltonian, walker_batch, trial
>   File "/ipie/estimators/local_energy_wicks.py", line 974, in local_energy_multi_det_trial_wicks_batch_opt
>     Lvo,
> ValueError: cannot assign slice from input of different size

The generation of the input file works, I see the error when trying to run AFQMC by calling 
> python /path/to/ipie/bin/ipie.py input.json > output.dat

**Comment by fdmalone** [comment]
This should be fixed by #153 . Note the default walker count (640) is chosen assuming the code is run in parallel. 640 walkers might be a bit slow for a serial calculation.

**Comment by michaelstreif** [comment]
Thanks! Can confirm that #153 fixed it.
