### ISSUE TITLE
Multi Slater Determinants (MSD) as Trial wavefunctions not possible for Fermi-Hubbard legacy code

### ISSUE THREAD

**Issue by michaelkaicher** [linusjoonho/ipie#155]
Hi, 

we have been playing around with your code and have been able to successfully run the AFQMC Fermi Hubbard example from your legacy folder when using a _single_ Slater determinant for the trial wavefunction $|\Psi_T\rangle$. 

However, when we wanted to use a multi-reference trial wavefunction "MSD" ( so sth that looks like [ [c1,c2,...,cK], [Psi1,Psi2,...,PsiK]], where K is the integer identical to the number of Slater determinants one wants to include in the trial wavefunction and Psik is a (N_modes x N_electrons matrix) ), we got the message that _MSD trial disabled at the moment_. 

Is there a working example for the Fermi Hubbard model with a MSD trial wavefunction, or sth like a quick fix? Apparently, your code does allow for MSD for molecular systems, so it must be possible to adapt that molecular MSD code to a Fermi-Hubbard Hamiltonian, right?

Cheers, 
Michael.

**Comment by fdmalone** [comment]
Currently anything under legacy isn't actively maintained (apart from tests running). Old features were kept around with the hope they could be resurrected carefully once the motivation was there. It shouldn't be difficult to bring back the Hubbard model but some refactoring of the propagator and wavefunction classes are required.

**Comment by linusjoonho** [comment]
Alternatively, you can try to run the Hubbard model through our newer code (continuous Hubbard-Stratonovich transform). Discrete transform can only be run by the legacy code at the moment.
