### ISSUE TITLE
Inconsistent ROHF energy

### ISSUE THREAD

**Issue by vvp-nsk** [linusjoonho/ipie#159]
Hi!

Trial wfn energy is wrong for the case of the ROHF trial. The problem is easy to reproduce:

1. pyscf_to_ipie.py -i 'fe-rohf.chk' -t 1.0e-7 -j 'input.json' 
    python -u ipie input.json | grep "Trial wfn energy is"
**# Trial wfn energy is (-1262.0756242894768+0j)**
2. pyscf_to_ipie.py -i 'fe-rohf.chk' -t 1.0e-7 -j 'input.json'  **--frozen-core 5**
     python -u ipie input.json | grep "Trial wfn energy is"
**# Trial wfn energy is (-1247.6351207932323+0j)**

**The reference ROHF energy reads -1262.37885948839.** 

Attached please find PySCF's chk file. 
[fe-rohf.zip](https://github.com/linusjoonho/ipie/files/9629566/fe-rohf.zip)

With best regards, 
Victor

**Comment by fdmalone** [comment]
#160 Should fix this. Thanks for raising the issue!
