### ISSUE TITLE
[BUG] GPU: numpy.linalg.LinAlgError: 3-dimensional array given. Array must be two-dimensional

### ISSUE THREAD

**Issue by vvp-nsk** [linusjoonho/ipie#166]
**Describe the bug**

Hi!

The ipie is crashing on GPU:

 There are unused GPUs (1 MPI tasks but 4 GPUs).  Check if this is really what you wanted.
 random seed is 28984271
 Trial wfn energy is (-2.143363122188042+0j)
 Getting propagator driver
 Getting WalkerBatchHandler
 Available memory on the node is 0.000 GB
 nwalkers                  : 10
 nwalkers_per_task         : 10
 dt                        : 0.005
 batched                   : True
 nsteps                    : 25
 nblocks                   : 1000
 nstblz                    : 5
 npop_control              : 5
 eqlb_time                 : 2.0
 neqlb                     : 400
 rng_seed                  : 28984271
 ntot_walkers              : 10

Traceback (most recent call last):
  File "run_afqmc.py", line 38, in <module>
    afqmc.run(comm=comm)
  File "/home/vivy/Devel/ipie.gpu/ipie/qmc/afqmc_batch.py", line 334, in run
    self.psi.orthogonalise(self.trial, self.propagators.free_projection)
  File "/home/vivy/Devel/ipie.gpu/ipie/walkers/walker_batch_handler.py", line 189, in orthogonalise
    detR = self.walkers_batch.reortho()
  File "/home/vivy/Devel/ipie.gpu/ipie/walkers/walker_batch.py", line 405, in reortho
    return self.reortho_batched()
  File "/home/vivy/Devel/ipie.gpu/ipie/walkers/walker_batch.py", line 450, in reortho_batched
    (self.phia, Rup) = qr(self.phia, mode=qr_mode)
  File "/sw/easybuild/software/CuPy/8.5.0-fosscuda-2020b/lib/python3.8/site-packages/cupy/linalg/_decomposition.py", line 243, in qr
    _util._assert_rank2(a)
  File "/sw/easybuild/software/CuPy/8.5.0-fosscuda-2020b/lib/python3.8/site-packages/cupy/linalg/_util.py", line 18, in _assert_rank2
    raise linalg.LinAlgError(
numpy.linalg.LinAlgError: 3-dimensional array given. Array must be two-dimensional

**To Reproduce**
Steps to reproduce the behavior along with minimal examples, including SCF jobs.

I am using the input from examples/06-gpu/:

`mpirun -np 1 python run_afqmc.py`

**Expected behavior**
Just should run and complete w/o error.

**Screenshots**

**Other information:**
 - Git: v0.1.0-7-g8d2072b (SHA-1: 8d2072b29978498f5c212b6365215426713dac99)
 - OS: Cent OS 
 - Version: 7

**Additional context**
The list of SW modules loaded is given below:

Currently Loaded Modules:
  1) SoftwareTree/Haswell    (S)  19) OpenMPI/4.0.5
  2) GCCcore/10.2.0               20) OpenBLAS/0.3.12
  3) zlib/1.2.11                  21) FFTW/3.3.8
  4) binutils/2.35                22) ScaLAPACK/2.1.0
  5) GCC/10.2.0                   23) bzip2/1.0.8
  6) CUDAcore/11.1.1              24) ncurses/6.2
  7) CUDA/11.1.1                  25) libreadline/8.0
  8) numactl/2.0.13               26) Tcl/8.6.10
  9) XZ/5.2.5                     27) SQLite/3.33.0
 10) libxml2/2.9.10               28) GMP/6.2.0
 11) libpciaccess/0.16            29) libffi/3.3
 12) hwloc/2.2.0                  30) Python/3.8.6
 13) libevent/2.1.12              31) pybind11/2.6.0
 14) Check/0.15.2                 32) SciPy-bundle/2020.11
 15) GDRCopy/2.1-CUDA-11.1.1      33) cuDNN/8.0.4.30-CUDA-11.1.1
 16) UCX/1.9.0-CUDA-11.1.1        34) NCCL/2.8.3-CUDA-11.1.1
 17) libfabric/1.11.0             35) cuTENSOR/1.2.2.5-CUDA-11.1.1
 18) PMIx/3.1.5                   36) CuPy/8.5.0

NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4  

The compute node is equipped by four NVIDIA K80 accelerators.

**Comment by fdmalone** [comment]
Looks like a cupy/numpy version info without batched QR @linusjoonho ?

**Comment by fdmalone** [comment]
@vvp-nsk What version of numpy/cupy are you using?

**Comment by fdmalone** [comment]
adding versbosity=2 to build_afqmc_driver(...,verbosity=2) in the example will print library info

**Comment by fdmalone** [comment]
Can't reproduce issue with cupy 10.5.0

**Comment by vvp-nsk** [comment]
Hi again!

The versions are listed below:
>>> cupy.__version__
'8.5.0'
>>> numpy.__version__
'1.19.4'

Just in case, the verbose output is also given below:

 Python interpreter: 3.8.6 (default, Nov 23 2020, 09:26:52)  [GCC 10.2.0]
 Using numpy v1.19.4 from: /sw/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages/numpy.
 - BLAS lib: openblas openblas
 - BLAS dir: /sw/easybuild/software/OpenBLAS/0.3.12-GCC-10.2.0/lib64
 Using scipy v1.5.4 from: /sw/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages/scipy.
 Using h5py v3.1.0 from: /home/vivy/.local/lib/python3.8/site-packages/h5py.
 Using mpi4py v3.0.3 from: /sw/easybuild/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages/mpi4py.
 - mpicc: /sw/easybuild/software/OpenMPI/4.0.5-gcccuda-2020b/bin/mpicc
 Using cupy v8.5.0 from: /sw/easybuild/software/CuPy/8.5.0-fosscuda-2020b/lib/python3.8/site-packages/cupy.
 - CUDA compute capability: 3.7
 - CUDA version: 11.01.0
 - GPU Type: 'Tesla K80'
 - GPU Mem: 11.173 GB
 - Number of GPUs: 4


With best regards, 
Victor

**Comment by vvp-nsk** [comment]
Hi!

I already requested to update the version of CuPy installed on our workhorse machine. The issue can be closed. 

Thank you!

With best regards, 
Victor
